apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    app: clickhouse
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: clickhouse
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: clickhouse
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 65532
      initContainers:
        - name: restore-clickhouse-backup
          image: {{ .Values.images.clickhouseRestore }}
          resources:
            requests:
              cpu: "0.2"
              memory: "128Mi"
            limits:
              cpu: "0.4"
              memory: "256Mi"
          env:
            - name: REMOVE_OLD_DATA_DIR
              value: "true"
            - name: DISABLE_PROGRESS
              value: "true"
            {{- include "s3Env" . | nindent 12 }}
        {{- include "clickhouseVolumeMounts" . | nindent 10 }}
      containers:
        - name: clickhouse
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
              ephemeral-storage: "5Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
              ephemeral-storage: "5Gi"
          image: {{ .Values.images.clickhouse }}
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
        # backup requires access to volume, so, it cannot be done using k8s cron job
        - name: clickhouse-backup
          image: {{ .Values.images.clickhouseBackup }}
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
            limits:
              # should be at least 512 because MinIO uploads in chunks (128MB by default) plus some internal buffers
              cpu: "0.2"
              memory: 512Mi
          env:
            - name: DISABLE_PROGRESS
              value: "true"
            - name: CLICKHOUSE
              value: "127.0.0.1:9000"
            {{- include "s3Env" . | nindent 12 }}
            # reduce memory usage - default part size is 128
            - name: UPLOAD_WORKER_COUNT
              value: "2"
            - name: UPLOAD_PART_SIZE
              value: "64"
          {{- include "clickhouseVolumeMounts" . | nindent 10 }}
      volumes:
        - name: clickhouse-data
          emptyDir: {}
        - name: s3
          secret:
            secretName: ij-perf-data-s3-rw
            items:
              - key: AWS_ACCESS_KEY_ID
                path: accessKey
              - key: AWS_SECRET_ACCESS_KEY
                path: secretKey
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  ports:
    - name: tcp
      port: 9000
      protocol: TCP
    - name: http
      port: 8123
      protocol: TCP
  selector:
    app: clickhouse