apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: nats
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: nats
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nats
          image: nats:2.1.8-scratch@sha256:58f4cc7757a15ffd8f476b74f9d5f199646235b25f85012e759f3cdf64b510a5
          resources:
            requests:
              cpu: "0.1"
              memory: "64Mi"
            limits:
              cpu: "0.2"
              memory: "128Mi"
          readinessProbe:
            tcpSocket:
              port: 4222
          livenessProbe:
            tcpSocket:
              port: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
    {{- include "common.labels" . | nindent 4 }}
spec:
  ports:
    - name: tcp
      port: 4222
      protocol: TCP
    - name: http
      port: 8222
      protocol: TCP
  selector:
    app: nats
    {{- include "common.selectorLabels" . | nindent 4 }}