apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tc-collector
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  # every 4 hours
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "common.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: tc-collector
              image: {{ .Values.images.collector }}
              resources:
                requests:
                  cpu: "0.2"
                  memory: 512Mi
                limits:
                  cpu: "0.4"
                  memory: 2Gi
              env:
                - name: TC_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: ij-perf-data-tc
                      key: token
                # memory limit — do not overload server
                - name: INSERT_WORKER_COUNT
                  value: "1"
                - name: INSERT_BATCH_SIZE
                  value: "1000"
                - name: NATS
                  value: "nats:4222"
                - name: CLICKHOUSE
                  value: "clickhouse:9000"
              volumeMounts:
                - mountPath: /etc/config
                  name: config
          imagePullSecrets:
            - name: ghcr
          volumes:
            - name: config
              configMap:
                name: tc-collector-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tc-collector-config
data:
  config.json: {{ .Values.collector | toJson | quote }}