defaultBaseImage: gcr.io/distroless/static-debian11:nonroot

baseImageOverrides:
  github.com/JetBrains/ij-perf-report-aggregator/cmd/clickhouse: ghcr.io/jetbrains/ij-perf-report-aggregator/clickhouse@sha256:7dc3e616b90942f9428ecafbf308b87fc7525bb713fb56ae955abd82c9a45e63