name: Build and push image to build application

on:
  workflow_dispatch:
  push:
    paths: 
      - "deployment/app-builder/**"
    branches: [ master ]

jobs:
  build:
    uses: jetbrains/ij-perf-report-aggregator/.github/workflows/reusable-image-build-push.yml@master
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    with:
      imageName: jetbrains/ij-perf-report-aggregator/app-builder
      dockerContextDir: deployment/app-builder
    secrets: inherit