name: Build and push image to build application

on:
  workflow_dispatch:
  push:
    paths: 
      - "deployment/app-builder/**"
    branches: [ master ]

jobs:
  build:
    uses: jetbrains/ij-perf-report-aggregator/.github/workflows/reusable-image-build-push.yml@master
    with:
      imageName: jetbrains/ij-perf-report-aggregator/app-builder
      dockerContextDir: deployment/app-builder
    secrets: inherit