name: Build and push ClickHouse image

on:
  workflow_dispatch:
  push:
    paths: 
      - "deployment/clickhouse/**"
    branches: [ master ]

jobs:
  build:
    uses: jetbrains/ij-perf-report-aggregator/.github/workflows/reusable-image-build-push.yml@master
    with:
      imageName: jetbrains/ij-perf-report-aggregator/clickhouse
      dockerContextDir: deployment/clickhouse
    secrets: inherit